#!/bin/bash

mcdir() {
  mkdir -p $@; cd $@
}

highlight () { grep --color -E "$1|$" "${@:2}" ; }

ua-install () {
local name=$(echo $1 | grep -o '[^/]*$')
  sudo update-alternatives --install /usr/local/bin/$name $name $1 100
}

sbt-what-depends() {
  sbt "whatDependsOn $(echo $@ | sed 's/:/ /g')"
}

replacelink() {
  [[ -L "$1" ]] || (echo 'not a link' && return)
  local src="$(readlink "$1")"
  rm -f "$1"
  cp -r "$src" "$1"
}

mvn-get() {
  local args=(
    'org.apache.maven.plugins:maven-dependency-plugin:3.0.2:copy'
    -Doverwrite=true
    -DoutputDirectory=$(pwd))
  if [[ "$1" == "--clean" ]]; then
    args+=("-Dmaven.repo.local=$(mktemp -d)")
    shift
  fi
  mvn "${args[@]}" -Dartifact="$@"
}

gethub() {
  local dir=$HOME/git/hub/${1%%\/*}
  mkdir -p $dir
  cd $dir
  git clone gh:"$@"
}

gh-remote-add() {
set -ex
  local repo="gh:$1/$(basename $(realpath $(__gitdir)/..))"
  git fetch "$repo" \
    && git remote add $1 "$repo" \
    && git fetch --all
set +ex
}

__git_continue() {
  git rebase --continue "$@" \
    || git cherry-pick --continue "$@" \
    || git merge --continue "@"
}

__git_abort() {
  git rebase --abort "$@" \
    || git cherry-pick --abort "$@" \
    || git merge --abort "$@"
}

__git_amend() {
  local ref head parent stash stash2
  [[ -n "$1" ]] &&
  ref=$(git rev-parse "$1") &&
  head=$(git rev-parse HEAD) &&
  [[ -n "$head" && -n "$ref" ]] &&
  parent=$(git rev-list --ancestry-path "$ref".."$head"| tail -1) &&
  stash=$(git stash create) &&
  [[ -n "$parent" && -n "$stash" ]] &&
  git reset --hard "$ref" &&
  git stash pop "$stash" &&
  git commit --amend "${@:2}" &&
  stash2=$(git stash create) &&
  git rebase --onto HEAD "$parent".."$head" ||
  echo 'Oops' >&2 && return 1

  [[ -n "$stash2" ]] && git stash pop "$stash2"
}
