#!/usr/bin/env zsh

# Load bash completion before zsh competions.
source $HOME/env/common/rc_helpers.sh
autoload -Uz compinit bashcompinit
compinit
bashcompinit

### Antegen
source ~/env/lib/antigen/antigen.zsh
# Load the oh-my-zsh's library.
antigen use oh-my-zsh
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle python
antigen bundle tmux
antigen bundle vi-mode
antigen bundle command-not-found
# Fish-like bundles
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting
#antigen bundle tarruda/zsh-autosuggestions
# Funtional stuff
antigen bundle Tarrasch/zsh-functional
antigen theme fishy
antigen apply
### END Antigen

ZKBD_FILE=~/env/zsh/.zkbd/$TERM-${${DISPLAY:t}:-$VENDOR-$OSTYPE}
source-if-exists $ZKBD_FILE

# Highlighting style
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_STYLES[path_approx]='fg=magenta,bold'

# Line load hook
zle-line-init() {
  # Enable autosuggestions automatically
  #zle autosuggest-start
}
zle -N zle-line-init

# Key-bindings
bindkey '^f' vi-forward-blank-word
bindkey  "${key[Home]}"    vi-beginning-of-line
bindkey  "${key[End]}"     vi-end-of-line

# Fix LDAP issue
unsetopt cdablevars

# per-tab history
local-history-substring-search-up() {
    zle set-local-history 1
    zle history-substring-search-up
    zle set-local-history 0
}
zle -N local-history-substring-search-up
local-history-substring-search-down() {
    zle set-local-history 1
    zle history-substring-search-down
    zle set-local-history 0
}
zle -N local-history-substring-search-down

# history-substring-search config
# bind UP and DOWN arrow keys
bindkey "${key[Up]}" local-history-substring-search-up
bindkey "${key[Down]}" local-history-substring-search-down

bindkey "^[[1;5A" history-substring-search-up    # [CTRL] + Cursor up
bindkey "^[[1;5B" history-substring-search-down  # [CTRL] + Cursor down

# Site mix-ins
MIX_INS=(
    $HOME/env/common/*
    $HOME/site-env/zsh/rc
)
eachf source-if-exists $MIX_INS
