#!/usr/bin/env zsh

### Antigen
source ~/env/lib/antigen/antigen.zsh
antigen init ~/env/zsh/antigen/rc

source ~/env/common/rc_helpers.sh
# autoload -Uz compinit bashcompinit
# compinit
# bashcompinit

ZKBD_FILE=~/env/zsh/.zkbd/xterm
source-if-exists $ZKBD_FILE

# Highlighting style
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_STYLES[path_approx]='fg=magenta,bold'

# Key-bindings
bindkey '^f'                  vi-forward-blank-word
bindkey  "${key[Home]}"       vi-beginning-of-line
bindkey  "${key[End]}"        vi-end-of-line
bindkey  "${key[PageUp]}"     vi-end-of-line
bindkey  "${key[PageDown]}"   vi-end-of-line

## per-tab history
local-history-substring-search-up() {
    zle set-local-history 1
    zle history-substring-search-up
    zle set-local-history 0
}
zle -N local-history-substring-search-up
local-history-substring-search-down() {
    zle set-local-history 1
    zle history-substring-search-down
    zle set-local-history 0
}
zle -N local-history-substring-search-down

## history-substring-search config
## bind UP and DOWN arrow keys
bindkey "${key[Up]}"   local-history-substring-search-up
bindkey "${key[Down]}" local-history-substring-search-down

bindkey "^[[1;5A"          history-substring-search-up    # [CTRL] + Cursor up
bindkey "^[[1;5B"          history-substring-search-down  # [CTRL] + Cursor down
bindkey "^[[1;5C"          vi-forward-word                # [CTRL] + Cursor right
bindkey "^[[1;5D"          vi-backward-word               # [CTRL] + Cursor left
bindkey "${key[PageUp]}"   history-substring-search-up
bindkey "${key[PageDown]}" history-substring-search-down

# Fix LDAP issue
unsetopt cdablevars

# Misc
setopt interactivecomments
setopt extended_glob

# TMUX
if [[ -n "${TMUX}" ]]; then
  eval $(tmux show-environment | sed -En "s/([^=]+)=(.*)/export \1='\2'/p")
fi

# Site mix-ins
MIX_INS=(
    $HOME/env/common/*
    $HOME/env/lib/docker-alias/zshrc
    $HOME/site-env/zsh/rc
)
eachf source-if-exists $MIX_INS

alias sp='source $HOME/env/zsh/rc'
